update

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -62,17 +62,18 @@ authenticate_to_org:
     - select_target_org
   script:
     - echo "Starting authentication job..."
-    - echo "Current directory "
-    - echo - $(pwd)
+    - echo "Current directory:"
+    - echo $(pwd)
     - echo "Listing files in .gitlab/scripts:"
     - ls -l .gitlab/scripts
-    - echo "Checking if authenticate-to-org.sh exists and is executable:"
-    - test -f .gitlab/scripts/authenticate-to-org.sh && echo "File exists" || echo "File missing"
-    - test -x .gitlab/scripts/authenticate-to-org.sh && echo "File is executable" || echo "File not executable"
-    - echo "Environment variables:"
-    - env
-    - echo "Attempting to run the script..."
-    - .gitlab/scripts/authenticate-to-org.sh "$ORG_ALIAS" "auth_file.json"
+    - echo "Checking if authenticate-to-org.sh exists:"
+    - test -f .gitlab/scripts/authenticate-to-org.sh && echo "Script exists" || echo "Script missing"
+    - echo "Attempting to run the authentication script using bash..."
+    - if [ ! -z "$ORG_ALIAS" ]; then
+        bash .gitlab/scripts/authenticate-to-org.sh "$ORG_ALIAS" "auth_file.json";
+      fi
+    - echo "Authentication job finished."
+
 
 
 # Create delta packages
